### ISSUE TITLE
Content for the About-Us page - Our Story

### ISSUE THREAD

**Issue by apoorv74** [CivicDataLab/website-new#15]
[Designs](https://whimsical.com/cdl-website-YWwu6X29JyX581An1i7KyV)

Sheet [About Us](https://docs.google.com/spreadsheets/d/1KbaWCUWr_BJaItBvgfCeZeccZoTdUcF6zGjBGW_pmvI/edit?usp=sharing).

**Comment by TheDataAreClean** [comment]
### **One Liner**
Use this sowing image / idea from our branding. ([Link](https://twitter.com/CivicDatalab/status/1178640371271819264/photo/1)) 

### **Our Story**
CivicDataLab works with the goal of harnessing data, tech, design and social science to strengthen the course of civic engagements in India. We believe in sowing seeds of change, trust and opportunities to enable citizens to engage better with public reforms.

### **The Team**: 
Our Bandhus are a motley crew of designers, researchers and technologists who are passionate to increase access to information and encourage, improve the civic participation in the country

Meet the individuals who work behind the scenes to make it all happen!

### **Work with Us**
Collaborate with us to sow the seeds of change !

@akkisagiraju @apoorv74 @Desingneer 

CC: @aruncdl

**Comment by TheDataAreClean** [comment]
@apoorv74 @akkisagiraju Please find the latest update on the `About Us` sheet [here](https://docs.google.com/spreadsheets/d/1KbaWCUWr_BJaItBvgfCeZeccZoTdUcF6zGjBGW_pmvI/edit?usp=sharing).

Updates Shared:
- Updated content Grid
- Title and Text for each section
- Images for available sections
