### ISSUE TITLE
Profile page - Update content for all bandhus

### ISSUE THREAD

**Issue by akkisagiraju** [CivicDataLab/website-new#25]
Content [here](https://docs.google.com/spreadsheets/d/1KbaWCUWr_BJaItBvgfCeZeccZoTdUcF6zGjBGW_pmvI/edit#gid=0)

**Comment by apoorv74** [comment]
@akkisagiraju please check the sheet and update the website. We can then ask members to check and update content if needed.

**Comment by apoorv74** [comment]
this issue is duplicated. Issue tracked #8
