### ISSUE TITLE
Content Requirements - Home Page

### ISSUE THREAD

**Issue by apoorv74** [CivicDataLab/website-new#39]
Image Requirements:
- [x] Update banner images
- [x] Update sector images
- [x] Verify if all partner logos are present

Text:
- [x] Add more content around pillars
- [x] Add content for blogs

Design:
- [x] Home Page Banner not communicating message optimally; the message is not getting through.
- [x] Update the design of the blog links; doesn't feel or look like links

**Comment by TheDataAreClean** [comment]
@akkisagiraju @apoorv74 
Please find the updated content of the `Home Page` tab of the following [sheet](https://docs.google.com/spreadsheets/d/1KbaWCUWr_BJaItBvgfCeZeccZoTdUcF6zGjBGW_pmvI/edit?usp=sharing).

Items Addressed:
- Title and copy of each section.
- Images and colours for setors.
- Need confirmation on banner.
