### ISSUE TITLE
Our Work - Design fixes

### ISSUE THREAD

**Issue by apoorv74** [CivicDataLab/website-new#40]
https://civicdatalab.in/website-new/sectors/

- [x] ~3~ 2 projects per row
- [x] Different colors for each sector
- [x] Bolder project titles
- [x] Add header title for the blogs
- [x] Update the font (same as the website) for the blog strip

Projects:
- [x] Primary Image  is too big.
- [x] Add quick links and partners on the left
- [x] Work heading on the navbar is not highlighted

@akkisagiraju please check.

**Comment by akkisagiraju** [comment]
@apoorv74 We are already doing the 3 projects per row on high resolution screens (2K+) but not on anything that's less than 1920px wide. Divya also suggested against doing it on normal screen resolutions as they look too cluttered.

**Comment by akkisagiraju** [comment]
Sticking with 2 projects per row on <1920px wide screens. On higher resolutions, there would be 3 projects per row.

**Comment by akkisagiraju** [comment]
Not sure what this means: Add header title for the blogs

**Comment by TheDataAreClean** [comment]
Hey @akkisagiraju . 

When we filter on a particular sector. The following section could be titled blogs. Also do you think we should move to the new design for these blogs too?

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/11213505/119794365-1ac03080-bef5-11eb-9e83-df995858c7c0.png">

**Comment by akkisagiraju** [comment]
@TheDataAreClean I added the project title just for differentiating among different projects in the sector. I have no strong opinions on this. We can also replace this with new blogs strip if we want to. But the problem is, there's no straightforward way to filter our blogs on Medium based on projects or sector.

**Comment by TheDataAreClean** [comment]
Hmmm. Then let's not for now @akkisagiraju  . Just a header is enough.

**Comment by apoorv74** [comment]
@akkisagiraju the blog strip on the home-page is looking much better than what it is here. If possible, we should follow the same design throughout the website. We can curate the blogs data in the same way as we're doing for other content, if that will help ? Let us know.

**Comment by apoorv74** [comment]
@akkisagiraju we can use tags to identify the blog posts for every sector. Every blog on CDL's publication is tagged under one of these categories:

![image](https://user-images.githubusercontent.com/5118689/119825147-49013880-bf14-11eb-8e01-a6372d1d32ff.png)

Can we use this logic to identify the posts ? We might still face issues to identify blogs for a project, to solve for that we can we can update the tags on medium and include a project-level tag as well. Can this be done ?

**Comment by akkisagiraju** [comment]
@apoorv74 I just looked at Medium's RSS feed response, and yes, what you are suggesting is possible. It can be done without a lot of effort.

![Screenshot from 2021-05-27 18-23-57](https://user-images.githubusercontent.com/7601150/119829558-fece8600-bf18-11eb-91e0-3a94c45eeb8f.png)

**Comment by apoorv74** [comment]
Update: 

Removed the blog strip. We have included a resources section which will have a list of blogs/articles/video. 

Blogs now have the project/sector tags in the content curation sheet.
