### ISSUE TITLE
Design Fixes - Team page

### ISSUE THREAD

**Issue by apoorv74** [CivicDataLab/website-new#43]
https://civicdatalab.in/website-new/team

- [x] 4 bandhus in one row
- [x] Lot of whitespace on the left
- [x] Current Job Openings can be below the Team heading (left side-bar)

**Comment by akkisagiraju** [comment]
> 4 bandhus in one row

This something both Divya (in her email) and I agreed to not do as it would be too crowded.

> Lot of whitespace on the left

That's how it is the design.

> Current job openings can be below the Team heading

I can add a simple link to the openings to the page but I'd appreciate Divya's input on this.

**Comment by akkisagiraju** [comment]
Sticking to 3 bandhus per row. Rest of the changes are done.

**Comment by akkisagiraju** [comment]
Make only the right part scrollable.

**Comment by apoorv74** [comment]
@akkisagiraju 

- [ ] I don't see the Job Opening's card on my screen. Scrolling thing is fixed though.  
- [ ] Copy the team description from the homepage and add it below **The Team** header
