### ISSUE TITLE
SEO fixes

### ISSUE THREAD

**Issue by apoorv74** [CivicDataLab/website-new#47]
@TheDataAreClean 's Comments :

1. Update the project work URL heirarchy.
> `civicdatalab.in/work/<sector>/<project>`

2. Update the Sector Links in Footer
> Each sector as a button in the footer.

**Comment by akkisagiraju** [comment]
The commit #8110cca fixes this issue.

**Comment by TheDataAreClean** [comment]
**New Additions**:

## Meta Tags:

```
<!-- Primary Meta Tags -->
<title>CivicDataLab | Data, Tech, Design, Social Science</title>
<meta name="title" content="CivicDataLab | Data, Tech, Design, Social Science">
<meta name="description" content="A research lab working on the intersection use data, tech, design and social science to strengthen the course of civic engagements in India.">

<!-- Open Graph / Facebook -->
<meta property="og:type" content="website">
<meta property="og:url" content="https://civicdatalab.in/website-new/">
<meta property="og:title" content="CivicDataLab | Data, Tech, Design, Social Science">
<meta property="og:description" content="A research lab working on the intersection use data, tech, design and social science to strengthen the course of civic engagements in India.">
<meta property="og:image" content="">

<!-- Twitter -->
<meta property="twitter:card" content="summary_large_image">
<meta property="twitter:url" content="https://civicdatalab.in/website-new/">
<meta property="twitter:title" content="CivicDataLab | Data, Tech, Design, Social Science">
<meta property="twitter:description" content="A research lab working on the intersection use data, tech, design and social science to strengthen the course of civic engagements in India.">
<meta property="twitter:image" content="">
```

**Meta Tag [Image](https://drive.google.com/file/d/1WbdosVvi6SBjYtEF6kHj-f0wotdHMRgw/view?usp=sharing)**

## Favicon

Logo [Image](https://drive.google.com/file/d/1WbdosVvi6SBjYtEF6kHj-f0wotdHMRgw/view?usp=sharing)

Will add more stuff later.

**Comment by akkisagiraju** [comment]
Added all the updated metatags.

**Comment by TheDataAreClean** [comment]
Hey @akkisagiraju . Only a couple of items left here.

1. Add a favicon for the website. (Image shared above)
2. Create a [sitemap](https://www.sitemaps.org/protocol.html) for the website.

Once you complete point `#2`, please let me know I will add the website to the Google Search Console.

CC: @apoorv74

**Comment by akkisagiraju** [comment]
These are done.
