### ISSUE TITLE
Sector - Law and Justice -  Content Review

### ISSUE THREAD

**Issue by apoorv74** [CivicDataLab/website-new#50]
- [x] Verifying project/sector descriptions
- [x] Check project/sector images
- [x] Check all resources that are added/missed
- [x] Check partner links
- [x] Check social-media links
- [x] Check if all bandhus are added on the project/sector pages

**Comment by apoorv74** [comment]
- [ ] Justice Hub URL needs to be updated on the [project page](https://civicdatalab.in/website-new/work/lawandjustice/justicehub/)
- [ ] Update Zombie Tracker URL on the [project page](https://civicdatalab.in/website-new/work/lawandjustice/zombietracker/)
- [ ] Update content for Zombie tracker
- [ ] Update content for Justice Hub
- [ ] Update content for CHILD RIGHTS LAWS IMPLEMENTATION TRACKER
- [ ] Add resources for the HAQ project

@akkisagiraju check and close.

**Comment by akkisagiraju** [comment]
@apoorv74 The above changes are done and are live.
