### ISSUE TITLE
Sector - Public Finance - Content Review

### ISSUE THREAD

**Issue by apoorv74** [CivicDataLab/website-new#54]
- [x] Verify project/sector descriptions
- [x] Check project/sector images
- [x] Check all resources that are added/missed
- [x] Check partner links
- [x] Check social-media links
- [x] Check if all bandhus are added on the project/sector pages

**Comment by aruncdl** [comment]
Thanks @apoorv74 . Have reviewed the content and made a few corrections. Added resources (blogs, videos etc.). Haven't added a cover image. Please let me know if there's anything missing @akkisagiraju

**Comment by aruncdl** [comment]
OBI project image - [new suggestion](https://drive.google.com/file/d/1Z-SrdU5ns9AnQykA0uAuZ3ROMhgUYMq4/view?usp=sharing)

PF Sector image - [new suggestion](https://drive.google.com/file/d/1xHPBgEhpFDoaj-1VLtVF5JR7ia7jFE3_/view?usp=sharing) - this one I'm not sure how we can use - we can freely use it with attribution. 

Requesting @preethical to check if the images for public procurement are appropriate. There seems to be some missing resources in the public procurement page, under the project name.

**Comment by apoorv74** [comment]
@aruncdl can you share the source for the PF sector image ?

**Comment by preethical** [comment]
@aruncdl could you elaborate? I see the resources, i had put in there in the project area. But there is not twitter, url, insta, facebook currently for public procurement to add.

**Comment by preethical** [comment]
@apoorv74 @aruncdl can someone tell me where I can put the appropriate image if need be?

**Comment by aruncdl** [comment]
@apoorv74 these are some of the options with their source

[Option 1](https://www.freepik.com/free-vector/business-performance-analysis-with-graphs_3425213.htm#page=1&query=magnifying%20glass&position=16)

[Option 2](https://www.freepik.com/free-vector/magnifying-glass-with-file-searching_5481505.htm#page=1&query=magnifying%20glass&position=28)

**Comment by apoorv74** [comment]
> 
> 
> @apoorv74 @aruncdl can someone tell me where I can put the appropriate image if need be?

[Here](https://drive.google.com/drive/u/0/folders/1cZwiwrvz6PVrKvucZqL5gijGqwhdHpd7)

**Comment by apoorv74** [comment]
@akkisagiraju please check the images and close.

**Comment by akkisagiraju** [comment]
@aruncdl Can we have a different image for PF sector? The license from Freepik says we have to explicitly include their website url and the text "Background vector created by rawpixel.com - www.freepik.com" in our footer or somewhere close to the image.

**Comment by aruncdl** [comment]
@akkisagiraju let's go with the image that's on right now for the launch imo, unless @gggodhwani can suggest something that works
