### ISSUE TITLE
Sector - Open Contracting - Content Review

### ISSUE THREAD

**Issue by apoorv74** [CivicDataLab/website-new#55]
- [x] Verifying project/sector descriptions
- [x] Check project/sector images
- [x] Check all resources that are added/missed
- [x] Check partner links
- [x] Check social-media links
- [x] Check if all bandhus are added on the project/sector pages

**Comment by preethical** [comment]
Done. Please review.

**Comment by apoorv74** [comment]
@preethical can you add the projects for which you have added content in the table above and mark ✔️ or ❌ . We can review then review. Also, do not close the issue, we'll do it after reviewing the content.

**Comment by apoorv74** [comment]
@preethical check this - #54 

[comment](https://github.com/CivicDataLab/website-new/issues/54#issuecomment-855346785) from @aruncdl

**Comment by preethical** [comment]
I have added an image for public procurement (called option-1) please feel free to use it or not. depending on how it looks on the page.

**Comment by apoorv74** [comment]
@akkisagiraju you can check this and close.

**Comment by akkisagiraju** [comment]
Updated the cover image.
