### ISSUE TITLE
Sector - Education - Content Review

### ISSUE THREAD

**Issue by apoorv74** [CivicDataLab/website-new#56]
- [x] Verifying project/sector descriptions
- [x] Check project/sector images
- [x] Check all resources that are added/missed
- [x] Check partner links
- [x] Check social-media links
- [x] Check if all bandhus are added on the project/sector pages

**Comment by TheDataAreClean** [comment]
Hey @apoorv74 . I have updated these.

**Comment by TheDataAreClean** [comment]
@akkisagiraju @apoorv74 

I have reviewed this and updates things at a few places across the sector and also the PF HAQ project.

**Comment by akkisagiraju** [comment]
Updated all the content from the latest data in the content curation sheet.
