### ISSUE TITLE
Sector - FOSS -  Content Review

### ISSUE THREAD

**Issue by apoorv74** [CivicDataLab/website-new#58]
- [x] Verifying project/sector descriptions
- [x] Check project/sector images
- [x] Check all resources that are added/missed
- [x] Check partner links
- [x] Check social-media links
- [x] Check if all bandhus are added on the project/sector pages

**Comment by preethical** [comment]
Done. Please review.

**Comment by apoorv74** [comment]
@preethical can you add the projects (for which you have added content in the sheet) in the table above and mark ✔️ or ❌ . We can review then review. Also, do not close the issue, we'll do it after reviewing the content.
