### ISSUE TITLE
Update sector card UI according to the latest XD

### ISSUE THREAD

**Issue by akkisagiraju** [CivicDataLab/website-new#60]

**Comment by apoorv74** [comment]
@akkisagiraju few issues i see with the cards:

- [ ] Keep the sector colors consistent. Clicking on a sector page, the color changes
- [ ] No line on hover for the first Card (Education)
- [ ] Display the entire text of sector descriptions on the card. We can trim the content if that will help.

**Comment by akkisagiraju** [comment]
@apoorv74 The three items are done and the changes are live now.
