### ISSUE TITLE
Fix scroll on all pages

### ISSUE THREAD

**Issue by apoorv74** [CivicDataLab/website-new#73]
As per the revised UI changes on the Team Page, update the scroll behavior for other pages:

- ~[ ] Bandhu Page~
- [x] Our Work 
- [x] Project Page
- [x] Sector Page

**Comment by apoorv74** [comment]
Discussion Thread - https://chat.civicdatalab.in/group/cdl-website?msg=34voFBMiEZm5PRk2r

**Comment by akkisagiraju** [comment]
Not doing this for bandhu page as mentioned on the thread linked above

**Comment by apoorv74** [comment]
@akkisagiraju Not working on my screen. Let's work this out.
