### ISSUE TITLE
Collate high res portrait pictures and quotes for team members's profile page

### ISSUE THREAD

**Issue by akkisagiraju** [CivicDataLab/website-new#8]
Share details [here](https://docs.google.com/spreadsheets/d/1KbaWCUWr_BJaItBvgfCeZeccZoTdUcF6zGjBGW_pmvI/edit#gid=0)

- [x] Abhinav
- [x] Akhil
- [x] Apoorv
- [x] Arpit Arora
- [x] Arun Sudarsan
- [x] Deepthi Chand
- [x] Gaurav Godhwani
- [x] Hemavathy L
- [x] Preethi Govindarajan
- [x] Samriddhi
- [x] Shashank Sharma
- [x] Shreya Agrawal
- [x] Upasana Hembram

**Comment by apoorv74** [comment]
@akkisagiraju please check the sheet and update the website. We can then ask members to check and update content if needed.
